# Generated by Django 6.0 on 2025-12-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('ph_level', models.DecimalField(decimal_places=1, help_text='pH Level (6.0-8.0)', max_digits=3)),
                ('chlorine_ppm', models.DecimalField(decimal_places=1, help_text='Free Chlorine (ppm)', max_digits=4)),
                ('alkalinity_ppm', models.IntegerField(help_text='Total Alkalinity (ppm)')),
                ('temperature_celsius', models.DecimalField(decimal_places=1, help_text='Water Temperature (°C)', max_digits=4)),
                ('water_clarity', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('algae', 'Algae Present')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=500, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
